# Steps for dataset and schema registration

steps:
  - step: dataset_registration
    description: Register the dataset in the system.
    parameters:
      dataset_name: "example_dataset"
      dataset_description: "This is an example dataset."
      owner: "data_team"

  - step: schema_registration
    description: Register the schema for the dataset.
    parameters:
      schema_name: "example_schema"
      schema_fields:
        - name: "field1"
          type: "string"
        - name: "field2"
          type: "integer"
        - name: "field3"
          type: "boolean"

  - step: virtual_dataset_registration
    description: Register a virtual dataset for the schema.
    parameters:
      virtual_dataset_name: "example_virtual_dataset"
      schema_name: "example_schema"
      query: "SELECT * FROM example_dataset"

  - step: physical_dataset_registration
    description: Register a physical dataset for the schema.
    parameters:
      physical_dataset_name: "example_physical_dataset"
      storage_location: "/path/to/storage"
      format: "parquet"

  - step: finalize_registration
    description: Finalize the registration process.
    parameters:
      confirmation: true
      notify_owner: true